import type { Metadata } from "next";
import { Lato } from "next/font/google";
import "./globals.css";
import Navbar from "./Components/Navbar";
import Footer from "./Components/Footer";

// Import the Lato font with the required weight
const lato = Lato({ 
  weight: ["400", "700"], // Specify the weights you need
  subsets: ["latin"] 
});

export const metadata: Metadata = {
  title: "JG TAX CONSULTANT",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={lato.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
